### ISSUE TITLE
XIAOMI FANG snapshot crashes homebridge?

### ISSUE THREAD

**Issue by StefanMeGit** [KhaosT/homebridge-camera-ffmpeg#112]
I don't know why, but my homebridge is always crashing when i try to watch the stream...

has anyone an idea? When i put **rtsp://192.168.1.162/unicast ** into VLC i can see the stream. :(

```
   "platform":"Camera-ffmpeg",
   "cameras":[
      {
         "name":"Camera 1",
         "videoConfig":{
            "source":"-rtsp_transport tcp -i rtsp://192.168.1.162/unicast",
            "stillImageSource":"-i rtsp://192.168.1.162/unicast -vframes 1 -r 1",
            "maxStreams":2,
            "maxWidth":1920,
            "maxHeight":1080,
            "maxFPS":30,
         }
      }
   ]
```
```
Camera 1 is running on port 45739.
-rtsp_transport tcp -i rtsp://192.168.1.162/unicast -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Zdk2U8m5Of9d6EILDTjJAKI5q6A1yJ6fJqat7aml srtp://192.168.1.86:57431?rtcpport=57431&localrtcpport=57431&pkt_size=1378
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)


[9/12/2017, 9:05:31 AM] Homebridge is running on port 51826.
[9/12/2017, 9:05:31 AM] Camera 1 is running on port 36619.
Snapshot -i rtsp://192.168.1.162/unicast -vframes 1 -r 1 -t 1 -s 480x270 -f image2 -
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by NorthernMan54** [comment]
If you look at the message, it is saying

Spawn ffmpeg ENOENT

Which means it can't find ffmpeg

**Comment by StefanMeGit** [comment]
hmm i did. But after reinstall now it works fine! 

But when i look on HOME, i got the snapshot and can watch the video only for a few seconds... it also looks a little bit like slowmotion and then the connection break up. When i close and open the HOME app i can watch again for a few seconds in slowmo.

**Comment by NorthernMan54** [comment]
What hardware are you using for homebridge?  Raspberry pi?  If so you need the rpi optimized version of ffmpeg,  look for the omx version.

**Comment by StefanMeGit** [comment]
Yes, i use a RPI3.

At the moment i get a perfect picture over VLC and rtsp://192.168.1.162/unicast . But on my home App i dont even get an screenshot or at least a stream! !? What did i wrong?

i used now following settings:

From https://github.com/legotheboss/homebridge-camera-ffmpeg-omx
```
  "platform": "Camera-ffmpeg-omx",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
        "source": "rtsp_transport -re -i rtsp://192.168.1.162/unicast",
        "stillImageSource": "-i rtsp://192.168.1.162/unicast -vframes 1 -r 1",
        "maxStreams": 2,
        "maxWidth": 720,
        "maxHeight": 480,
        "maxFPS": 10
      }
    }
  ]
}
```
and Xiaomi Fang Hack with these settings:

```
start()
{
  LOG=/dev/null
  echo "Starting RTSP server..."
  snx_rtsp_server -W 1280 -H 720 -Q 10 -b 2048 -a >$LOG 2>&1 &
  echo "$!" > "$PIDFILE"
}
```

**Comment by StefanMeGit** [comment]
After delete the camera and add it agin in the home app, i get a screenshot after a few seconds. But stream still doesn't work!

**Comment by StefanMeGit** [comment]
#98

**Comment by niccolospa** [comment]
I'm having the exact same issue, someone sorted this out?
