### ISSUE TITLE
0.1.4 Audio Support - Service is not defined

### ISSUE THREAD

**Issue by mriksman** [KhaosT/homebridge-camera-ffmpeg#149]
I get the error
```
/usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:41
    cameras.forEach(function(cameraConfig) {
            ^
ReferenceError: Service is not defined
    at /usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:55:37
    at Array.forEach (native)
    at ffmpegPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:41:13)
```

When this code tries to run;
`        var microphoneService = new Service.Microphone("Microphone");
` 
What am I missing?

**Comment by KhaosT** [comment]
Ah `Service` is missing. v0.1.5 should fix this.
