### ISSUE TITLE
events.js:183 - Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by TURSTY** [KhaosT/homebridge-camera-ffmpeg#178]
Hi guys. I have Homebridge running in Windows 10. Followed the install instructions on this hub and added my camera config (copied from an old Config.json file that used to work on a Rpi). I have managed to add the camera to HomeKit, but as soon as I open the app on my iphone, it crashed Homebridge with the below error:

[2018-4-20 17:09:32] [Camera-ffmpeg] Snapshot from Garage Cam at 480x270
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\User>

I read an older issue and someone indicated this was because Camera-ffmpeg was not installed, however the initial start of Homebridge indicates it is correct?

C:\Users\User>homebridge
[2018-4-20 17:09:22] Loaded plugin: homebridge-camera-ffmpeg
[2018-4-20 17:09:22] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2018-4-20 17:09:22] ---
[2018-4-20 17:09:23] Loaded plugin: homebridge-homeseer-plugin-2018
homebridge API version: 2.2
[2018-4-20 17:09:23] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[2018-4-20 17:09:23] ---
[2018-4-20 17:09:23] Loaded config.json with 0 accessories and 2 platforms.
[2018-4-20 17:09:23] ---
[2018-4-20 17:09:23] Loading 2 platforms...
[2018-4-20 17:09:23] [HomeSeer] Initializing HomeSeer platform...
[2018-4-20 17:09:23] [HomeSeer] System default periodic polling rate set to: 10 seconds
[2018-4-20 17:09:23] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
Load homebridge-HomeSeerPlatform.HomeSeer
[2018-4-20 17:09:23] Garage Cam is running on port 53283.

Any ideas how I can get this working? It used to work on a Rpi a friend built me but I dont have the passwords to get into it, so have installed Homebridge on the same NUC my Homeseer software runs on.

**Comment by adrum** [comment]
Make sure you are able to run the ffmpeg executable. I'm not sure exactly how to make this work on Windows, but this error is typically thrown when ffmpeg is not available or installed properly.

**Comment by TURSTY** [comment]
Yip...im about as dum as the come!!! followed a youtube vid to install FFMPEG on windows (super simple) and its working.
