### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by WoodySlum** [KhaosT/homebridge-camera-ffmpeg#18]
Hi !

Thank you for the great job you're doing.
However, I got a crash when starting homebridge, can you help me ?

```
homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:253
  var controlService = new Service.CameraControl();
                       ^

TypeError: Service.CameraControl is not a function
    at FFMPEG.createCameraControlService (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:253:24)
    at new FFMPEG (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:113:8)
    at /var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/index.js:52:26
    at Array.forEach (native)
    at ffmpegPlatform.didFinishLaunching (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/index.js:41:13)
    at emitNone (events.js:67:13)
    at API.emit (events.js:166:7)
    at Server.run (/var/www/xxxx/plugins/Siri/homebridge/lib/server.js:90:13)
    at module.exports (/var/www/xxxx/plugins/Siri/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/var/www/xxxx/plugins/Siri/homebridge/bin/homebridge:17:22)
```

**Comment by WoodySlum** [comment]
I just take a look on requirements in package.json. I have node 4.2. I'll try to upgrade to node 5.0 to check if the error still remains.

**Comment by KhaosT** [comment]
You need to make sure your homebridge is at least v0.4 or newer

**Comment by WoodySlum** [comment]
Not better, same issue.

Is Node 5 mandatory ?
I installed ffmpeg

Here is my settings :
**Node**
```
/usr/local/bin/node -v
v4.2.1
```

**Homebridge**
```
./homebridge -V
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
0.4.9
```

Any other idea ?

**Comment by KhaosT** [comment]
and you still getting an error of ``TypeError: Service.CameraControl is not a function``?

**Comment by WoodySlum** [comment]
Yes, still the same issue. In doubt, I do a `sudo npm install homebridge -g`even if I'm starting homebridge from sources.

Same result :
```
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 537-29-962 │     
    └────────────┘     
                       
/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:253
  var controlService = new Service.CameraControl();
                       ^

TypeError: Service.CameraControl is not a function
    at FFMPEG.createCameraControlService (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:253:24)
    at new FFMPEG (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/ffmpeg.js:113:8)
    at /var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/index.js:52:26
    at Array.forEach (native)
    at ffmpegPlatform.didFinishLaunching (/var/www/xxxx/plugins/Siri/homebridge-plugins/homebridge-camera-ffmpeg/index.js:41:13)
    at emitNone (events.js:67:13)
    at API.emit (events.js:166:7)
    at Server.run (/var/www/xxxx/plugins/Siri/homebridge/lib/server.js:90:13)
    at module.exports (/var/www/xxxx/plugins/Siri/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/var/www/xxxx/plugins/Siri/homebridge/bin/homebridge:17:22)
```

**Comment by WoodySlum** [comment]
I re-installed homebridge and now the error disappear. However, my camera supports only MJPEG streaming, your plugin only allows rtsp right ?

**Comment by KhaosT** [comment]
it depends on what ffmpeg compiled with. If you can have ffmpeg to play a MJPEG stream then is should also work.

**Comment by WoodySlum** [comment]
Ok i'll give a try ! Thank you !
