### ISSUE TITLE
Need help with Google Drive Setup....

### ISSUE THREAD

**Issue by ctschach** [KhaosT/homebridge-camera-ffmpeg#196]
I followed everything like as described to setup google drive but i'm running into an issue with the last step:

```
mer@playground:/usr/lib/node_modules/homebridge-camera-ffmpeg$ node quickstart.js
Authorize this app by visiting this url:  https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&client_id=XXXXXXX7-XXXXXXXXXXXXmutm.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Enter the code from that page here: 4/AADGpkB3WDSI7BrjNt9595A-StimZwLkqKnaHXXXXXXXXXdQBfo6PI
fs.js:159
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:159:9)
    at Object.fs.writeFile (fs.js:1278:14)
    at storeToken (/home/oscar/src/homebridge-camera-ffmpeg/drive.js:199:8)
    at /home/oscar/src/homebridge-camera-ffmpeg/drive.js:180:13
    at /home/oscar/src/homebridge-camera-ffmpeg/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/home/oscar/src/homebridge-camera-ffmpeg/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/home/oscar/src/homebridge-camera-ffmpeg/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/oscar/src/homebridge-camera-ffmpeg/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
```

Any ideas?

**Comment by aliceforware** [comment]
got error on last step after update? please help


c:\Users\Alice>npm update  -g homebridge-camera-ffmpeg

c:\Users\Alice>cd appdata\roaming\npm\node_modules\homebridge-camera-ffmpeg

c:\Users\Alice\AppData\Roaming\npm\node_modules\homebridge-camera-ffmpeg>node quickstart
Authorize this app by visiting this url:  https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&client_id=1052444813005-8bkjkic9gvl1apgbcq9it0cpl6q4v2h0.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Enter the code from that page here: 4/fADq_13h8a53haiXbebtHUz_gzrGa9znHFQJcq0MuKPYV8XUDVt5c-k
Error while trying to retrieve access token { Error: invalid_grant
    at Request._callback (c:\Users\Alice\AppData\Roaming\npm\node_modules\homebridge-camera-ffmpeg\node_modules\google-auth-library\lib\transporters.js:81:15)
    at Request.self.callback (c:\Users\Alice\AppData\Roaming\npm\node_modules\homebridge-camera-ffmpeg\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (c:\Users\Alice\AppData\Roaming\npm\node_modules\homebridge-camera-ffmpeg\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (c:\Users\Alice\AppData\Roaming\npm\node_modules\homebridge-camera-ffmpeg\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 400 }
