### ISSUE TITLE
Cant get Carlo cameras to stream or notification snapshots

### ISSUE THREAD

**Issue by rob74lee** [KhaosT/homebridge-camera-ffmpeg#276]
Here is what I get. Please help.

[2/9/2019, 4:28:26 PM] Homebridge is running on port 51826.
[2/9/2019, 4:28:26 PM] Harvard is running on port 49685.
[2/9/2019, 4:28:58 PM] [Camera-ffmpeg] Retrieving Arlo URL for camera index : 0
error : Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-camera-ffmpeg/arlo.py", line 4, in <module>
    from Arlo import Arlo
ImportError: No module named Arlo

[2/9/2019, 4:28:59 PM] [Camera-ffmpeg] 
[2/9/2019, 4:28:59 PM] [Camera-ffmpeg] Snapshot from Harvard at 480x270
ffmpeg -i  -t 1 -s 480x270 -f image2 -
[2/9/2019, 4:28:59 PM] [Camera-ffmpeg] An error occurs while making snapshot request
[2/9/2019, 4:28:59 PM] [Camera-ffmpeg] { Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-i', '', '-t', '1', '-s', '480x270', '-f', 'image2', '-' ] }
[2/9/2019, 4:29:09 PM] [Camera-ffmpeg] Retrieving Arlo URL for camera index : 0
error : Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-camera-ffmpeg/arlo.py", line 4, in <module>

**Comment by perote2000** [comment]
It happen the same to me, 2 differents Raspberry pi (B model 2 and B model 3 with raspian with desktop and recommended software).  newy installed some days ago.
sudo apt-get install ffmpeg >> ffmpeg already installed >>  (7:3.2.12-1~deb9u1+rpt1).

[3/15/2019, 2:51:23 PM] [Camera-ffmpeg] An error occurs while making snapshot request
[3/15/2019, 2:51:23 PM] [Camera-ffmpeg] { Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-i',
     'http://10.3.0.78/cgi-bin/snapshot.cgi?channel=1&loginuse=XXXX&loginpas=XXXXXX',
     '-t',
     '1',
     '-s',
     '480x270',
     '-f',
     'image2',
     '-' ] }

this happen with snapsht image and when I try to te de video stream also...


[3/15/2019, 3:03:56 PM] [Camera-ffmpeg] Start streaming video from Camera Frente Sala with 1280x720@200kBit
ffmpeg -re -i rtsp://10.3.0.78:554/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif -map 0:0 -vcodec h264_omx -pix_fmt yuv420p -r 5 -f rawvideo -x264-params intra-refresh=1:bframes=0 -vf scale=1280:720 -b:v 200k -bufsize 200k -maxrate 200k -payload_type 99 -ssrc 1910020 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params BHCUlvde6dSxFCmGChX3QReqUJCeudslm9/DZS1g srtp://10.3.5.107:62943?rtcpport=62943&localrtcpport=62943&pkt_size=188 -loglevel debug
[3/15/2019, 3:03:56 PM] [Camera-ffmpeg] An error occurs while making stream request
[3/15/2019, 3:03:56 PM] [Camera-ffmpeg] { Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-re',
     '-i',
     'rtsp://10.3.0.78:554/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif',
     '-map',
     '0:0',
     '-vcodec',
     'h264_omx',
     '-pix_fmt',
     'yuv420p',
     '-r',
     '5',
     '-f',
     'rawvideo',
     '-x264-params',
     'intra-refresh=1:bframes=0',
     '-vf',
     'scale=1280:720',
     '-b:v',
     '200k',
     '-bufsize',
     '200k',
     '-maxrate',
     '200k',
     '-payload_type',
     '99',
     '-ssrc',
     '1910020',
     '-f',
     'rtp',
     '-srtp_out_suite',
     'AES_CM_128_HMAC_SHA1_80',
     '-srtp_out_params',
     'BHCUlvde6dSxFCmGChX3QReqUJCeudslm9/DZS1g',
     'srtp://10.3.5.107:62943?rtcpport=62943&localrtcpport=62943&pkt_size=188',
     '-loglevel',
     'debug' ] }
[3/15/2019, 3:03:56 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2

**Comment by perote2000** [comment]
Now.. researching more Ive figureout that it happen due ffmped is not installed inside docker....
So I had to intall manually in docker startup script by adding apk add --no-cache ffmpeg ffmpeg-libs
