### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by Ratjetoe** [KhaosT/homebridge-camera-ffmpeg#28]
I get this error message after starting homebridge.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I can pair my camera in the Home app. But no stream is showing. What should I do?

**Comment by Ratjetoe** [comment]
Forgot to install ffmpeg..my bad :(
