### ISSUE TITLE
Homebridge on Debian 10 ffmpeg error

### ISSUE THREAD

**Issue by gdefranc** [KhaosT/homebridge-camera-ffmpeg#386]
Please help 

Debian
Linux iot 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

homebridge -V
0.4.50
nodejs -v
v12.13.0

npm -v
6.12.0

nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] Loaded config.json with 0 accessories and 3 platforms.
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] ---
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] Loaded plugin: homebridge-camera-ffmpeg
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] ---
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] Loaded plugin: homebridge-config-ui-x
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] Registering platform 'homebridge-config-ui-x.config'
nov 07 14:04:10 iot homebridge[19264]: [2019-11-7 14:04:10] ---
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Loaded plugin: homebridge-foscamcamera
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Registering platform 'homebridge-foscamcamera.FoscamCamera'
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] ---
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Loaded plugin: homebridge-ws
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Registering platform 'homebridge-lib.Lib'
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Registering platform 'homebridge-ws.WS'
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] ---
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Loading 3 platforms...
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] [Ingresso] Initializing FoscamCamera platform...
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] [Config] Initializing config platform...
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] [Config] Spawning homebridge-config-ui-x with PID 19284
nov 07 14:04:11 iot homebridge[19264]: [2019-11-7 14:04:11] Loading 0 accessories...

{
	"bridge": {
		"name": "Casa mia",
		"username": "xxxxxxxxx",
		"port": 51827,
		"pin": "036-95-444"
	},
	"description": "Domotica della casa.",
	"platforms": [{
			"platform": "Camera-ffmpeg",
			"cameras": {
				"name": "test camera",
				"videoConfig": {
					"source": "-re -i rtsp://username:pwd@172.31.121.61//cam1/onvif-h264-1",
					"stillImageSource": "-i http://username:pwd@172.31.121.61/ISAPI/Streaming/channels/101/picture",
					"maxStreams": 2,
					"maxWidth": 1920,
					"maxHeight": 1080,
					"maxFPS": 30
				}
			}
		},
		{
   "platform": "config",
   "name": "Config",
   "port": 4000,
   "sudo": false
		}
	]
}

**Comment by gdefranc** [comment]
Sorry
follow log error
[2019-11-7 17:08:12] TypeError: cameras.forEach is not a function
nov 07 17:08:12 iot homebridge[4168]:     at ffmpegPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:45:13)
nov 07 17:08:12 iot homebridge[4168]:     at API.emit (events.js:215:7)
nov 07 17:08:12 iot homebridge[4168]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
nov 07 17:08:12 iot homebridge[4168]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
nov 07 17:08:12 iot homebridge[4168]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
nov 07 17:08:12 iot homebridge[4168]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
nov 07 17:08:12 iot homebridge[4168]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
nov 07 17:08:12 iot homebridge[4168]:     at Module.load (internal/modules/cjs/loader.js:812:32)
nov 07 17:08:12 iot homebridge[4168]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
nov 07 17:08:12 iot homebridge[4168]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
nov 07 17:08:12 iot homebridge[4168]:     at internal/main/run_main_module.js:17:11
