### ISSUE TITLE
Installed on Synology NAS - no video on iPhone

### ISSUE THREAD

**Issue by resgroupmsr** [KhaosT/homebridge-camera-ffmpeg#401]
Here's what I've got running.  Homebridge is installed and running with Docker on the Synology.  Homebridge shows up in Apple Home on devices, Camera shows up in Home app but camera shows with 'no response'.  In Homebridge running on the Synology I can see that the camera is creating image snapshots and outside of the Synology the camera is in fact fully functional.  Here are some log details:

[12/24/2019, 2:23:20 PM] Homebridge is running on port 52501.
[12/24/2019, 2:23:20 PM] Driveway Camera is running on port 46356.
[12/24/2019, 2:23:20 PM] Please add [Driveway Camera] manually in Home app. Setup Code: 031-45-154
[12/24/2019, 2:23:21 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270
[12/24/2019, 2:24:31 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270
[12/24/2019, 2:27:54 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270
[12/24/2019, 2:30:42 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270
[12/24/2019, 2:32:03 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270
[12/24/2019, 2:33:04 PM] [Camera ffmpeg] Snapshot from Driveway Camera at 480x270

I have 6 cameras to add, this config is only for first one, where you see xxxxx I've taken out personal details.  

Any ideas would be appreciated.

{
    "bridge": {
        "name": "Homebridge 8E7C",
        "username": "xxxxxx",
        "port": 52501,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Driveway Camera",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xxxxxxx@192.168.2.240:1935/h264Preview_01_main",
                        "stillImageSource": "-i http://192.168.2.240:1935/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Comment by resgroupmsr** [comment]
[12/24/2019, 10:26:46 PM] [Camera ffmpeg] Start streaming video from Driveway Camera with 1280x720@299kBit
ffmpeg rtsp://xxxxxxxxx:1935/h264Preview_01_sub -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 13537177 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params c48DvcCYLyiq0neTqEIs3vgYW5+Ptlsv8pBeaNzC srtp://192.168.2.114:50452?rtcpport=50452&localrtcpport=50452&pkt_size=1316 -loglevel debug
[12/24/2019, 10:26:46 PM] [Camera ffmpeg] An error occurs while making stream request
[12/24/2019, 10:26:46 PM] [Camera ffmpeg] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    'rtsp://xxxxxxxxx:1935/h264Preview_01_sub',
    '-map',
    '0:0',
    '-vcodec',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-r',
    '10',
    '-f',
    'rawvideo',
    '-tune',
    'zerolatency',
    '-b:v',
    '299k',
    '-bufsize',
    '299k',
    '-maxrate',
    '299k',
    '-payload_type',
    '99',
    '-ssrc',
    '13537177',
    '-f',
    'rtp',
    '-srtp_out_suite',
    'AES_CM_128_HMAC_SHA1_80',
    '-srtp_out_params',
    'c48DvcCYLyiq0neTqEIs3vgYW5+Ptlsv8pBeaNzC',
    'srtp://192.168.2.114:50452?rtcpport=50452&localrtcpport=50452&pkt_size=1316',
    '-loglevel',
    'debug'
  ]
}
[12/24/2019, 10:26:46 PM] [Camera ffmpeg] ERROR: FFmpeg exited with code -2

**Comment by resgroupmsr** [comment]
It appears you cannot get this to work on a Synology NAS using FFMPEG
