### ISSUE TITLE
Error ffmpeg on MAC

### ISSUE THREAD

**Issue by ChrisJary** [KhaosT/homebridge-camera-ffmpeg#41]
Hello,

I've an error when i open the stream video in AppHome.
Homebridge is installed to my MAC.
The plugin is installed correctly...
The stream video work on VLC.
I don't understand!

the error log:

events.js:160
throw er; // Unhandled 'error' event
^

Error: spawn ffmpeg ENOENT
at exports._errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dmckillican** [comment]
I have the same issue, also on a Mac. I get the following error

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by KhaosT** [comment]
YOU NEED TO INSTALL FFMPEG FIRST...

**Comment by dmckillican** [comment]
errr... well now I feel stupid - it's working, thanks! :)

**Comment by ChrisJary** [comment]
of course!
Sorry... 
it's working
