### ISSUE TITLE
I can't see camera in home app

### ISSUE THREAD

**Issue by quizatsaderac** [KhaosT/homebridge-camera-ffmpeg#477]
**After install the plug-in and configuring it with tested configuration : Sannce 1080P IP Cameras ( name NVR for me), home kit has discovered the camera and install it, but home said "camera no response" and message in HOOBS : 

[entrée] Snapshot from NVR at 480:270
[entrée] An error occurs while making snapshot request
I test the rtsp path in VLC and all is find.did i make a configuration error ?**

**Logs:**

```
<!-- 03/05/2020 à 23:06:25 - Loaded plugin "homebridge-eveatmo".
03/05/2020 à 23:06:27 - Loaded plugin "homebridge-harmony".
03/05/2020 à 23:06:27 - Loaded plugin "homebridge-platform-wemo".
03/05/2020 à 23:06:27 - Loaded plugin "homebridge-tado-ac".
03/05/2020 à 23:06:27 - Loaded plugin "homebridge-thekeys".
03/05/2020 à 23:06:27 - Loaded plugin "homebridge-tuya-web".
03/05/2020 à 23:06:28 - Loaded plugin "homebridge-tydom".
03/05/2020 à 23:06:29 - [Tydom] Creating tydom client with username='xxxxxxxxx' and hostname='mediation.tydom.com'
03/05/2020 à 23:06:29 - [salon] HarmonyPlatform Init
03/05/2020 à 23:06:29 - [eveatmo platform] Loading new data from API for: weatherstation
03/05/2020 à 23:06:29 - [The Keys] Create new instance of TK accessory
03/05/2020 à 23:06:29 - [The Keys] Starting a TK locker device with name 'maison'...
03/05/2020 à 23:06:29 - [The Keys] Gateway ip: 192.168.1.xx
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Configuring cached accessory [Terrasse applique] bfa93a4edd85adf878qiwc 9472658f-29e3-4deb-a714-a14e9a79d36e
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Configuring cached accessory [Entrée 1] 60847532c44f33964d22 e09651ca-0a98-4000-bd59-91df4d8e7028
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Configuring cached accessory [Terrasse 1] bf8dba93a0eb9100333ojw a7c5ea55-a6fd-4bc9-8aab-1b995f32df70
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Configuring cached accessory [Terrasse 2] bf0d183fcb068ab8336bqy 55029045-f517-45e4-8c44-9b34064dd16f
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Configuring cached accessory [Entrée 2] 60847532c44f33a765cf 80b38e1d-2923-4054-9dd9-6664939200bb
03/05/2020 à 23:06:29 - [salon] DidFinishLaunching
03/05/2020 à 23:06:29 - [salon] (salon)INFO - Loading activities...
03/05/2020 à 23:06:29 - [TuyaWebPlatform] Initializing TuyaWebPlatform...
03/05/2020 à 23:06:30 - [The Keys] check lockers
03/05/2020 à 23:06:30 - NVR is running on port 40999.
03/05/2020 à 23:06:30 - [BelkinWeMo] Online: WeMo Motion [08863BC4A830]
03/05/2020 à 23:06:30 - [BelkinWeMo] Online: bureau [B4750E0E7C64]
03/05/2020 à 23:06:31 - [BelkinWeMo] Online: lampadaire [EC1A5982A834]
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Adding: Terrasse applique (light / bfa93a4edd85adf878qiwc)
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Existing Accessory found [Terrasse applique] [bfa93a4edd85adf878qiwc] [9472658f-29e3-4deb-a714-a14e9a79d36e]
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Adding: Entrée 1 (light / 60847532c44f33964d22)
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Existing Accessory found [Entrée 1] [60847532c44f33964d22] [e09651ca-0a98-4000-bd59-91df4d8e7028]
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Adding: Terrasse 1 (light / bf8dba93a0eb9100333ojw)
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Existing Accessory found [Terrasse 1] [bf8dba93a0eb9100333ojw] [a7c5ea55-a6fd-4bc9-8aab-1b995f32df70]
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Adding: Terrasse 2 (light / bf0d183fcb068ab8336bqy)
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Existing Accessory found [Terrasse 2] [bf0d183fcb068ab8336bqy] [55029045-f517-45e4-8c44-9b34064dd16f]
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Adding: Entrée 2 (light / 60847532c44f33a765cf)
03/05/2020 à 23:06:31 - [TuyaWebPlatform] Existing Accessory found [Entrée 2] [60847532c44f33a765cf] [80b38e1d-2923-4054-9dd9-6664939200bb]
03/05/2020 à 23:06:31 - [Tydom] Successfully connected to Tydom hostname='mediation.tydom.com' with username='XXXXXXXXXXXX'
[Tydom] Successfully connected to Tydom hostname='mediation.tydom.com' with username='xxxxxxxxxxxxxxxx'
03/05/2020 à 23:06:32 - HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
03/05/2020 à 23:06:32 - HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
03/05/2020 à 23:06:32 - [eveatmo platform] Initializing platform accessory "xxxxxxxx
03/05/2020 à 23:06:32 - [eveatmo platform] Initializing platform accessory "xxxxxxxx Pluie"...
03/05/2020 à 23:06:32 - [eveatmo platform] Initializing platform accessory "xxxxxxxx Exterieur"...
03/05/2020 à 23:06:32 - [eveatmo platform] Initializing platform accessory "xxxxxxxx Chambre"...
03/05/2020 à 23:06:32 - [TadoAC] Initializing platform accessory "séjour Tado"...
03/05/2020 à 23:06:32 - HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
03/05/2020 à 23:06:32 - Bridge is running on port 51826.
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Film sur la télé
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Apple TV sur le videoprojecteur
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : platine Vinyle
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Xbox
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Film sur le videoprojecteur
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : la tele
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Xbox sur le videoprojecteur
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Apple TV
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : La musique sur l'ampli
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Xbox sur la télé
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Musique 5.1
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Discovered Activity : Tele sur Ampli
03/05/2020 à 23:06:33 - [salon] (salon)INFO - Loading general mute Switch...
03/05/2020 à 23:06:34 - [The Keys] check lockers
03/05/2020 à 23:06:34 - [Tydom] Found new tydom device named="bureau" with id="de30f12e-eb77-42f0-a7c9-37f6e8d6bc45"
03/05/2020 à 23:06:34 - [Tydom] Updating accessory named="bureau" with id="de30f12e-eb77-42f0-a7c9-37f6e8d6bc45"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="chambre angi" with id="0b920d33-fbf9-4ed8-b1cc-59c124adc2e3"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="chambre angi" with id="0b920d33-fbf9-4ed8-b1cc-59c124adc2e3"
03/05/2020 à 23:06:35 - [The Keys] check lockers
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="chambre parent" with id="dd5f863f-96af-42d0-a210-e38c778ab3cd"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="chambre parent" with id="dd5f863f-96af-42d0-a210-e38c778ab3cd"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="panoramique" with id="eb1b9b43-2931-45f9-9612-173cb745297f"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="panoramique" with id="eb1b9b43-2931-45f9-9612-173cb745297f"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="chambre marianne" with id="3d40c963-e06a-42c5-8087-1c55372c0473"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="chambre marianne" with id="3d40c963-e06a-42c5-8087-1c55372c0473"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="chambre quentin" with id="068b0d07-40fb-4ee8-b3e1-deeeae6898c8"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="chambre quentin" with id="068b0d07-40fb-4ee8-b3e1-deeeae6898c8"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="salon" with id="34833768-9ab6-468f-ab18-ff250613effc"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="salon" with id="34833768-9ab6-468f-ab18-ff250613effc"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="cuisine" with id="d5b43f57-a09e-476b-8a6a-206e714df556"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="cuisine" with id="d5b43f57-a09e-476b-8a6a-206e714df556"
03/05/2020 à 23:06:35 - [Tydom] Found new tydom device named="Terrasse" with id="eebdaecf-08c2-4833-9046-7a492b9a21cd"
03/05/2020 à 23:06:35 - [Tydom] Updating accessory named="Terrasse" with id="eebdaecf-08c2-4833-9046-7a492b9a21cd"
03/05/2020 à 23:06:36 - [Tydom] Found new tydom device named="Chauffage general" with id="13699283-31de-4df0-a586-2cb6677c613b"
03/05/2020 à 23:06:36 - [Tydom] Updating accessory named="Chauffage general" with id="13699283-31de-4df0-a586-2cb6677c613b"
03/05/2020 à 23:06:36 - [Tydom] Found new tydom device named="Salle d’eau" with id="9f01acf3-cecb-4bfe-9ea0-bb1e9bf015e2"
03/05/2020 à 23:06:36 - [Tydom] Updating accessory named="Salle d’eau" with id="9f01acf3-cecb-4bfe-9ea0-bb1e9bf015e2"
03/05/2020 à 23:06:36 - [Tydom] Found new tydom device named="Salle de bain" with id="55dca6e2-dd2b-46b4-ae85-25ce9a285555"
03/05/2020 à 23:06:36 - [Tydom] Updating accessory named="Salle de bain" with id="55dca6e2-dd2b-46b4-ae85-25ce9a285555"
03/05/2020 à 23:06:37 - [Tydom] Unsupported firstUsage="" for endpoint with id="1584222204"
03/05/2020 à 23:06:38 - [Tydom] Properly loaded 12-accessories
03/05/2020 à 23:06:38 - [The Keys] state of maison: 0
03/05/2020 à 23:06:38 - [The Keys] Calling url: http://192.168.1.xx/locker_status
03/05/2020 à 23:06:38 - [The Keys]    body: identifier=xxxxxxxxxxxxxxxxxxxxxxxxxxxx=
03/05/2020 à 23:06:39 - [The Keys] check lockers
03/05/2020 à 23:06:40 - [The Keys] check lockers
03/05/2020 à 23:06:41 - [The Keys] current state of maison: 0
03/05/2020 à 23:06:41 - [The Keys] current state of maison: 0
03/05/2020 à 23:06:41 - [The Keys] {"status": "Door open", "code": 50, "id":xxxx, "version":73, "position":22, "rssi": -66, "battery":7291}
03/05/2020 à 23:06:44 - [The Keys] check lockers
03/05/2020 à 23:06:45 - [The Keys] check lockers
03/05/2020 à 23:06:49 - [The Keys] check lockers
03/05/2020 à 23:06:50 - [The Keys] check lockers
03/05/2020 à 23:06:53 - [BelkinWeMo] WeMo Motion - Motion Sensor: Detected
03/05/2020 à 23:06:54 - [The Keys] check lockers
03/05/2020 à 23:06:55 - [The Keys] check lockers
03/05/2020 à 23:06:57 - [BelkinWeMo] WeMo Motion - no motion timer started [60 secs]
03/05/2020 à 23:06:59 - [BelkinWeMo] Online: Insecticide [08863BC4E1E0]
03/05/2020 à 23:06:59 - [The Keys] check lockers
03/05/2020 à 23:07:00 - [The Keys] check lockers
03/05/2020 à 23:07:04 - [The Keys] check lockers
03/05/2020 à 23:07:05 - [The Keys] check lockers
03/05/2020 à 23:07:09 - [The Keys] check lockers
03/05/2020 à 23:07:10 - [The Keys] check lockers
03/05/2020 à 23:07:14 - [The Keys] current state of maison: 0
03/05/2020 à 23:07:14 - [The Keys] current state of maison: 0
03/05/2020 à 23:07:14 - [TadoAC] séjour Mode is  OFF
03/05/2020 à 23:07:14 - [TadoAC] séjour Current Temperature is 24.33ºC
03/05/2020 à 23:07:14 - [The Keys] check lockers
03/05/2020 à 23:07:15 - [The Keys] check lockers
03/05/2020 à 23:07:19 - [The Keys] check lockers
03/05/2020 à 23:07:20 - [The Keys] check lockers
03/05/2020 à 23:07:24 - [The Keys] check lockers
03/05/2020 à 23:07:25 - [The Keys] check lockers
03/05/2020 à 23:07:29 - [The Keys] check lockers
03/05/2020 à 23:07:30 - [The Keys] check lockers
03/05/2020 à 23:07:34 - [The Keys] check lockers
03/05/2020 à 23:07:35 - [The Keys] check lockers
03/05/2020 à 23:07:39 - [The Keys] check lockers
03/05/2020 à 23:07:40 - [The Keys] check lockers
03/05/2020 à 23:07:44 - [The Keys] check lockers
03/05/2020 à 23:07:45 - [The Keys] check lockers
03/05/2020 à 23:07:49 - [The Keys] check lockers
03/05/2020 à 23:07:50 - [The Keys] check lockers
03/05/2020 à 23:07:55 - [The Keys] check lockers
03/05/2020 à 23:07:55 - [The Keys] check lockers
03/05/2020 à 23:07:55 - [BelkinWeMo] WeMo Motion - Motion Sensor: Detected
03/05/2020 à 23:07:57 - [entrée] Snapshot from NVR at 480:270
03/05/2020 à 23:07:57 - [entrée] An error occurs while making snapshot request
03/05/2020 à 23:07:57 - [BelkinWeMo] WeMo Motion - Motion Sensor: Clear; no motion timer completed
03/05/2020 à 23:07:59 - [BelkinWeMo] WeMo Motion - no motion timer started [60 secs]
03/05/2020 à 23:08:00 - [The Keys] check lockers
03/05/2020 à 23:08:00 - [The Keys] check lockers
03/05/2020 à 23:08:05 - [The Keys] check lockers
03/05/2020 à 23:08:05 - [The Keys] check lockers
**03/05/2020 à 23:08:07 - [entrée] Snapshot from NVR at 480:270
03/05/2020 à 23:08:07 - [entrée] An error occurs while making snapshot request -->**

**here is the part of error log when i tapped in the camera on iphone:**

04/05/2020 à 13:16:24 - [entrée] Snapshot from NVR at 480:270
04/05/2020 à 13:16:24 - [entrée] An error occurs while making snapshot request
04/05/2020 à 13:16:24 - [entrée] Snapshot from Camera at 480:270
04/05/2020 à 13:16:24 - [entrée] An error occurs while making snapshot request
04/05/2020 à 13:16:26 - (node:920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
04/05/2020 à 13:16:26 - at Object.ip.address (/home/hoobs/.hoobs/node_modules/ip/lib/ip.js:370:32)
04/05/2020 à 13:16:26 - at FFMPEG.prepareStream (/home/hoobs/.hoobs/node_modules/homebridge-camera-ffmpeg/ffmpeg.js:267:27)
04/05/2020 à 13:16:26 - at LegacyCameraSourceAdapter.prepareStream (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/camera/Camera.ts:60:23)
04/05/2020 à 13:16:26 - at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:948:21
04/05/2020 à 13:16:26 - at runMicrotasks ()
04/05/2020 à 13:16:26 - at processTicksAndRejections (internal/process/task_queues.js:93:5)
04/05/2020 à 13:16:26 - (node:920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
04/05/2020 à 13:16:26 - (node:920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Homebridge Config:**

```json
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://xxxxxxxxxxxx",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hunters-green",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "xxxxxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "TheKeys",
            "plugin_map": {
                "plugin_name": "homebridge-thekeys",
                "index": 0
            },
            "name": "The Keys",
            "locker_name": "xxxxx",
            "identifier": "xx",
            "code": "xxxxxx",
            "ip": "192.168.1.xx"
        }
    ],
    "platforms": [
        {
            "platform": "Tydom",
            "plugin_map": {
                "plugin_name": "homebridge-tydom"
            },
            "hostname": "mediation.tydom.com",
            "username": "xxxxx",
            "password": "xxxx"
        },
        {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            }
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "salon",
            "hubIP": "192.168.1.xx",
            "hubName": "salon",
            "publishAllTVAsExternalAccessory": "false",
            "TVAccessory": "false",
            "switchAccessories": "true",
            "publishGeneralMuteSwitch": "true",
            "publishGeneralVolumeSlider": "false",
            "publishSwitchActivitiesAsIndividualAccessories": "true",
            "publishDevicesAsIndividualAccessories": "false",
            "publishSequencesAsIndividualAccessories": "false",
            "publishHomeControlsAsIndividualAccessories": "false"
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxx",
                "password": "xxxxxxxxxx",
                "countryCode": "+33",
                "platform": "tuya",
                "pollingInterval": 90
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "TadoAC",
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxxxx",
            "plugin_map": {
                "plugin_name": "homebridge-tado-ac"
            }
        },
        {
            "platform": "eveatmo",
            "plugin_map": {
                "plugin_name": "homebridge-eveatmo"
            },
            "name": "eveatmo platform",
            "ttl": 540,
            "extra_co2_sensor": false,
            "co2_alert_threshold": 1000,
            "auth": {
                "client_id": "xxxxxxxxxxx",
                "client_secret": "xxxxxxxxx",
                "username": "xxxxxxxxxxxxxxxxxx",
                "password": "xxxxxxxxxxxxx"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "NVR",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.xxx/user=xxxxx_password=xxxxxxxx_channel=1_stream=1.sdp?real_stream",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30
                    }
                }
            ],
            "name": "entrée",
            "interfaceName": "nvr"
        }
    ]
}
```

**![IMG_1485](https://user-images.githubusercontent.com/59254528/80926340-fd26a300-8d96-11ea-873b-51860a534b27.png)**

**Environment:**

* **Node.js Version**:         12.13.1
* **NPM Version**:              how I can find in HOOBS ?
* **Homebridge Version**: . how I can find in HOOBS ?
* **Homebridge Camera FFmpeg               Version**: 0.1.19 publié 5/2/2020
* **Homebridge Config UI X Plugin Version**:  how I can find in HOOBS ?
* **Operating System**: HOOBS 3.2.3  Raspbian  Raspberry pi 2

**Comment by quizatsaderac** [comment]
hello,here is the part of error log when i tapped in the camera on iphone:

04/05/2020 à 13:16:24 - [entrée] Snapshot from NVR at 480:270
04/05/2020 à 13:16:24 - [entrée] An error occurs while making snapshot request
04/05/2020 à 13:16:24 - [entrée] Snapshot from Camera at 480:270
04/05/2020 à 13:16:24 - [entrée] An error occurs while making snapshot request
04/05/2020 à 13:16:26 - (node:920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
04/05/2020 à 13:16:26 - at Object.ip.address (/home/hoobs/.hoobs/node_modules/ip/lib/ip.js:370:32)
04/05/2020 à 13:16:26 - at FFMPEG.prepareStream (/home/hoobs/.hoobs/node_modules/homebridge-camera-ffmpeg/ffmpeg.js:267:27)
04/05/2020 à 13:16:26 - at LegacyCameraSourceAdapter.prepareStream (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/camera/Camera.ts:60:23)
04/05/2020 à 13:16:26 - at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:948:21
04/05/2020 à 13:16:26 - at runMicrotasks (<anonymous>)
04/05/2020 à 13:16:26 - at processTicksAndRejections (internal/process/task_queues.js:93:5)
04/05/2020 à 13:16:26 - (node:920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
04/05/2020 à 13:16:26 - (node:920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

thanks for your help.

**Comment by jonasophie** [comment]
Hello,
Does you rtsp stream works on VLC ?
Try to add « debug » to true, it may help to understand the error

**Comment by quizatsaderac** [comment]
hello,
Yes, the rstp stream works on VLC.
OK, I will try " debug " 
thanks.

**Comment by quizatsaderac** [comment]
hello,
here is the debug log on one cam:
11/05/2020 à 10:38:14 - ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.1.150/user=xxxxx_password=xxxxx_channel=1_stream=0.cgi?real_stream -t 1 -s 480x270 -f image2 -
11/05/2020 à 10:38:14 - [dvrSannce] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-rtsp_transport',
    'tcp',
    '-re',
    '-i',
    'rtsp://192.168.1.xx/user=xxxxx_password=xxxxx_channel=1_stream=0.cgi?real_stream',
    '-t',
    '1',
    '-s',
    '480x270',
    '-f',
    'image2',
    '-'
  ]
}


not being a specialist I cannot interpret the error :(

**Comment by jonasophie** [comment]
It seems ENOENT is for Error No Entry

Have you installed FFmpeg on the raspberry ?

**Comment by quizatsaderac** [comment]
no, I used HOOBS. I just install plug-in camera-ffmpeg.
ffmpeg isn't included in the plugin ?

**Comment by jonasophie** [comment]
Since 3.1.20 hoobs comes with ffmpeg prepacked

**Comment by jonasophie** [comment]
https://www.reddit.com/r/HOOBS/comments/eptegd/can_somebody_help_with_camera_ffmpeg_omx/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by quizatsaderac** [comment]
Thanks for help.
I re-install ffmpeg with this command : wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -
And 2 of my camera works ! !  :) 
the others must have a configuration error.
thank you for help !

**Comment by quizatsaderac** [comment]
![IMG_1487](https://user-images.githubusercontent.com/59254528/81559635-0d8adf00-9390-11ea-8563-c1bf3d9b895d.png)
actually a config error
