### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by neonightmare** [KhaosT/homebridge-camera-ffmpeg#6]
```
Hi got this...

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
pi@raspberrypi ~ $ events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
```
    
Any idea?

**Comment by KhaosT** [comment]
@neonightmare you need install ffmpeg first.

**Comment by neonightmare** [comment]
Thx, will try..
