### ISSUE TITLE
Error on startup after first install

### ISSUE THREAD

**Issue by iCarl** [KhaosT/homebridge-camera-ffmpeg#68]
I'm getting:

```
/usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:41
    cameras.forEach(function(cameraConfig) {
            ^

TypeError: cameras.forEach is not a function
    at ffmpegPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-camera-ffmpeg/index.js:41:13)
    at emitNone (events.js:91:20)
    at API.emit (events.js:185:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

My setup looks like this:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:23:3D:E3:CE:30",
    "port": 51826,
    "pin": "111-11-111"
  },
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "platforms": [
    {
      "platform": "Server",
      "port": 8765,
      "name": "Homebridge Server",
      "log": "systemd",
      "restart": "sudo systemctl restart homebridge"
    },
    {
      "platform": "AqaraPlatform",
      "sid": [
        "xxxxx"
      ],
      "password": [
        "xxxxx"
      ]
    },
    {
      "platform": "Camera-ffmpeg",
      "cameras": {
        "name": "kamera",
        "videoConfig": {
          "source": "-re -i rtsp://10.0.1.33/unicast",
          "maxStreams": 2,
          "maxWidth": 1280,
          "maxHeight": 720,
          "maxFPS": 10
        }
      }
    }
  ],
  "accessories": []
}
```

**Comment by KhaosT** [comment]
Cameras should be an array. You declared it as a dictionary. Check sample config. Hint: don't ignore the [ ].

**Comment by iCarl** [comment]
Changed to this:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:23:3D:E3:CE:30",
    "port": 51826,
    "pin": "111-11-111"
  },
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "platforms": [
    {
      "platform": "Server",
      "port": 8765,
      "name": "Homebridge Server",
      "log": "systemd",
      "restart": "sudo systemctl restart homebridge"
    },
    {
      "platform": "AqaraPlatform",
      "sid": [
        "xxxxx"
      ],
      "password": [
        "xxxxx"
      ]
    },
    {
      "platform": "Camera-ffmpeg",
      "cameras": [
        {
          "name": "Camera Name",
          "videoConfig": {
            "source": "-re -i rtsp://10.0.1.33/unicast",
            "maxStreams": "2",
            "maxWidth": "1280",
            "maxHeight": "720",
            "maxFPS": "10"
          }
        }
      ]
    }
  ],
  "accessories": []
}
```

Should bo correct now, it doesn't throw any errors, but the camera doesn't appear in Home

**Comment by iCarl** [comment]
It works!!! Thanks!
