### ISSUE TITLE
Error on Foscam

### ISSUE THREAD

**Issue by marcodesantis71** [KhaosT/homebridge-camera-ffmpeg#87]
Hi,

when I try to view a live stremain I receive this error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
I use NPM & Hombridge on os x

**Comment by NorthernMan54** [comment]
ENOENT means file not found, so you need to install ffmpeg.  If your on a RPI, the recommended version is here

https://github.com/legotheboss/homebridge-camera-ffmpeg-omx
